Repository chaosblade-io/chaosblade-box-fe, pull requests merged in 2021-03, with the labels that each got.

#5 add translations
  src/locales/en.js
  src/locales/zh.js
  src/pages/Machine/Probe/Register/index.js
Labels: type/enhancement

#6 fix scenario parameter value when updating experiment
  src/pages/Experiment/Creating/KubernetesExperiment.js
  src/pages/Experiment/Creating/ScenarioStep.js
  src/pages/Experiment/Creating/index.js
  src/reducers/ExperimentCreating.js
Labels: difficulty/easy, type/enhancement

#7 fix node selected when creating experiment
  src/pages/Experiment/Creating/MachineStep.js
  src/pages/Experiment/Detail/index.js
Labels: difficulty/easy, type/bug

#8 optimize kubernetes experiment under disable collect
  src/pages/Experiment/Creating/ExperimentSteps.js
  src/pages/Experiment/Creating/KubernetesExperiment.js
Labels: difficulty/easy, type/enhancement

#10 fix container experiment under collect disabled
  src/pages/Experiment/Creating/KubernetesExperiment.js
Labels: difficulty/easy, type/bug

#14 add scenario translation
  src/constants/ScenarioConstants.js
  src/locales/en.js
  src/locales/zh.js
  src/pages/Component/Metadata/navigation.js
  src/pages/Scenario/Detail/ParameterList.js
  src/pages/Scenario/Detail/ScenarioInfo.js
  src/pages/Scenario/Detail/ScenarioInfoForm.js
  src/pages/Scenario/List/ScenarioList.js
Labels: difficulty/easy, type/enhancement

#17 feature: add change locale interface
  src/Console.js
  src/actions/Actions/index.js
  src/actions/Types/index.js
  src/pages/Sider/index.js
  src/reducers/Sider.js
  src/reducers/index.js
  src/sagas/Sider.js
  src/sagas/index.js
  src/services/SiderApi.js
Labels: type/enhancement

#16 fix chaostools market detail
  src/actions/Actions/index.js
  src/actions/Types/index.js
  src/pages/Chaostools/Detail/Scenarios.js
  src/pages/Chaostools/Detail/index.js
  src/reducers/ChaostoolsDetail.js
Labels: type/bug

#18 fix table search
  src/libs/Search/index.js
  src/pages/Error/index.js
  src/pages/Experiment/Creating/index.js
  src/pages/Experiment/List/ExperimentList.js
Labels: type/bug

#21 release v0.3.1 version
  public/index.html
  src/locales/en.js
  src/locales/zh.js
  src/pages/Chaostools/Detail/Deploy.js
  src/pages/Chaostools/Detail/Scenarios.js
  src/pages/Chaostools/Market/MarketList.js
  src/pages/Chaostools/Market/index.js
  src/pages/Sider/index.js
  src/sagas/Chaostools.js
Labels: release
